from array import array
from cmath import pi
import json
from lib2to3.pytree import Node
import math
from multiprocessing.sharedctypes import Array
from platform import node
from zmq import DRAFT_API
from random import Random, random

Target = int(input(""))
x = {i for i in range(1,1000)}

row = {i for i in x if i + i == Target}

print(row)
 Node.json.random.randn()
 random.randn(0, i for i in range(0,50,x,y) while x in.json{find.locate(file("In.function()_click._random.randin(Insert).Collen"))})



def crocks():
   int(math.floor(pow(pi, 2)))

if crocks() :
    print("Valided")
else:
    print("Error")
